framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
            roundrobin: '%env(SLACK_DSN)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
            roundrobin: '%env(TWILIO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['sms/twilio']
            high: ['sms/twilio']
            medium: ['chat/slack']
            low: ['chat/slack']
